name: Static analysis

on:
  push:
    branches: [ master ]
  pull_request: null

jobs:
  sa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "lowest"
      - run: composer install --prefer-dist --prefer-lowest --no-progress --no-suggest
      - run: php vendor/bin/phpstan.phar analyse src
