name: Nette Tester

on:
  push:
    branches: [ master ]
  pull_request: null

jobs:
  tester:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "lowest"

      - name: Run tests
        run: vendor/bin/tester tests -C -s
